spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: odiya
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(ah9S7zNFgpypCEn+BH3zCGorts/7AwvYXWPzfX40b5kaDho6wDwEMNioCSX37h/FSq536qzgCh3efC2vLl6uz6oT3MZduVXqYN3G+sVVVNJfqd7HOvGgAjeSeiy7sv9C)
    username: ENC(mluTiRa0QUdOfdC/truNcw==)
    password: ENC(oWB0jD2lS1+y/SOFHbs9KpE9IpG0p2VZ)
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    properties:
      hibernate:
        default_schema: odiya
      default_batch_fetch_size: 100 # 한번에 묶어서 쿼리보내는 갯수
      time_zone: UTC
#    hibernate:
#      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: foo # server 1
    template:
      default-topic: chanel

aligo:
  api_key: ENC(dYrjtxEjTMYfrvqrQ2RxTWHpTFaeDkEMV0VmfuTlUYFkac5rQ0iPW5oJIeI5SU41)
