spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: odiya
  jwt:
    secret: ${JWT_SECRET}
    expired: ${JWT_EXPIRED:604800000}
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 1 # 추후 rds-proxy 를 도입 하면 해당 값을 0으로 합니다.
      minimum-idle: 0
      idle-timeout: 10000  # 10 seconds
      max-lifetime: 20000  # 20 seconds (matching Lambda timeout)
      connection-timeout: 2000  # 2 seconds
      validation-timeout: 1000  # 1 second
      leak-detection-threshold: 15000  # 15 seconds
  jpa:
    properties:
      hibernate:
        default_schema: odiya
      time_zone: UTC
    open-in-view: false
